pythonRequirements:
  noDeploy: []    # https://github.com/UnitedIncome/serverless-python-requirements/issues/241#issuecomment-421355568
  dockerizePip: true
  fileName: ../../requirements.txt
  useDownloadCache: false
  useStaticCache: false

iamRoleStatements: # permissions for all of your functions can be set here
  Effect: Allow
  Action: # Gives permission to DynamoDB tables in a specific region
    - dynamodb:DescribeTable
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
  Resource: "arn:aws:dynamodb:*:*:*"

region: ${file(../../config.${self:provider.stage}.json):REGION}
environment:
  REGION: ${file(../../config.${self:provider.stage}.json):REGION}
  STAGE: ${self:provider.stage}
  AUTH0_DOMAIN: ${file(../../config.${self:provider.stage}.json):AUTH0_DOMAIN}
  AUTH0_AUDIENCE: ${file(../../config.${self:provider.stage}.json):AUTH0_AUDIENCE}
  AUTH0_CLIENT_ID: ${file(../../config.${self:provider.stage}.json):AUTH0_CLIENT_ID}
  AUTH0_CLIENT_SECRET: ${file(../../config.${self:provider.stage}.json):AUTH0_CLIENT_SECRET}
  AUTH0_MANAGEMENT_API_CLIENT_ID: ${file(../../config.${self:provider.stage}.json):AUTH0_MANAGEMENT_API_CLIENT_ID}
  AUTH0_MANAGEMENT_API_CLIENT_SECRET: ${file(../../config.${self:provider.stage}.json):AUTH0_MANAGEMENT_API_CLIENT_SECRET}
  AUTH0_CLIENT_PUBLIC_KEY: ${file(../../public_key.${self:provider.stage})}
  AUTH0_CONNECTION: ${file(../../config.${self:provider.stage}.json):AUTH0_CONNECTION}
  SIGNUP_ORIGIN_URL: ${file(../../config.${self:provider.stage}.json):SIGNUP_ORIGIN_URL}
  S3_UPLOADS_BUCKET_NAME: ${file(../../config.${self:provider.stage}.json):S3_UPLOADS_BUCKET_NAME}
  ROLLBAR_SECRET: ${file(../../config.${self:provider.stage}.json):ROLLBAR_SECRET}
  AUTHORIZER_ARN: ${cf:SP-AUTH-${self:provider.stage}.AuthLambdaFunctionQualifiedArn}

corsStatements:
  origin: '*' # <-- Specify allowed origin. If required, allowed origin can be set to point from webapp deployment URL.
  headers: # <-- Specify allowed headers
    - Content-Type
    - X-Amz-Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - Access-Control-Allow-Headers
    - Access-Control-Allow-Origin
  allowCredentials: false

prune:
  automatic: true
  number: 3